# ProGuard rules for Unity AAR
# Generated by Unity - customize for your project

-keep public class com.unity3d.** {
    public <methods>;
    public <fields>;
}

# Keep Unity player classes
-keep public class com.unity3d.player.UnityPlayer {
    public void callStatic(string, string, string);
    public void UnitySendMessage(string, string, string);
}

# Keep Android lifecycle
-keep public class android.app.Activity {
    public void onCreate(android.os.Bundle);
    public void onDestroy();
    public void onPause();
    public void onResume();
}

# Keep Firebase classes
-keep public class com.google.firebase.** {
    public <methods>;
    public <fields>;
}

# Keep Gson for JSON serialization
-keep class com.google.gson.** {
    public <methods>;
    public <fields>;
}

# Keep UnityBridge class
-keep class com.unity3d.player.UnityBridge {
    public static <methods>;
}