# Auto-generated
CATEGORIES = [
    {"id": "per_te", "name": "Per Te", "icon": "⭐", "adult": False, "premium": False, "description": "Personaggi selezionati in base ai tuoi interessi"},
    {"id": "romantici", "name": "Romantici", "icon": "💕", "adult": False, "premium": False, "description": "Personaggi romantici e sognatori per conversazioni intime e poetiche"},
    {"id": "amicizia", "name": "Amicizia", "icon": "🤝", "adult": False, "premium": False, "description": "Amici fedeli e compagni di avventure per chiacchiere leggere"},
    {"id": "fantasy", "name": "Fantasy", "icon": "🧙", "adult": False, "premium": False, "description": "Personaggi magici e leggendari da mondi incantati"},
    {"id": "horror", "name": "Horror", "icon": "👻", "adult": False, "premium": True, "mvc_cost": 200, "description": "Entita oscure e misteriose per brividi e suspense"},
    {"id": "anime", "name": "Anime", "icon": "🎮", "adult": False, "premium": False, "description": "Personaggi ispirati al mondo degli anime e manga"},
    {"id": "scuola", "name": "Scuola", "icon": "🎓", "adult": False, "premium": False, "description": "Insegnanti e studenti per conversazioni educative"},
    {"id": "gamer", "name": "Gamer", "icon": "🕹️", "adult": False, "premium": False, "description": "Giocatori e personaggi virtuali per sfide e gaming"},
    {"id": "detective", "name": "Detective", "icon": "🕵️", "adult": False, "premium": False, "description": "Investigatori e agenti per misteri da risolvere"},
    {"id": "medicina", "name": "Medicina", "icon": "🏥", "adult": False, "premium": False, "description": "Medici e professionisti della salute"},
    {"id": "business", "name": "Business", "icon": "💼", "adult": False, "premium": False, "description": "Imprenditori e coach per consigli professionali"},
    {"id": "viaggi", "name": "Viaggi", "icon": "✈️", "adult": False, "premium": False, "description": "Esploratori e viaggiatori per racconti di avventure"},
    {"id": "motivazione", "name": "Motivazione", "icon": "💪", "adult": False, "premium": False, "description": "Motivatori e mentori per ispirazione e crescita personale"},
    {"id": "cucina", "name": "Cucina", "icon": "🍝️", "adult": False, "premium": False, "description": "Chef e appassionati di cucina per ricette e sapori"},
    {"id": "tecnologia", "name": "Tecnologia", "icon": "💻", "adult": False, "premium": False, "description": "Hacker e ingegneri per conversazioni tech"},
    {"id": "tecnici", "name": "Tecnici", "icon": "🔧", "adult": False, "premium": False, "description": "Esperti tecnici per consulenze professionali su programmazione e matematica"},
    {"id": "storia", "name": "Storia", "icon": "🏺", "adult": False, "premium": False, "description": "Storici e archeologi per viaggi nel passato"},
    {"id": "supereroi", "name": "Supereroi", "icon": "🤜", "adult": False, "premium": False, "description": "Eroi con superpoteri per avventure epiche"},
    {"id": "sopravvivenza", "name": "Sopravvivenza", "icon": "🏕️", "adult": False, "premium": False, "description": "Survivalist e esploratori per sfide nella natura"},
    {"id": "sci-fi", "name": "Sci-Fi", "icon": "🚀", "adult": False, "premium": False, "description": "Personaggi del futuro per conversazioni cosmiche"},
    {"id": "sport", "name": "Sport", "icon": "⚽", "adult": False, "premium": False, "description": "Atleti e istruttori per conversazioni sportive"},
    {"id": "esperti", "name": "Esperti Professionali", "icon": "💼", "adult": False, "premium": False, "description": "Consulenti e professionisti avanzati per business, marketing e finanza"},
    {"id": "creativi", "name": "Creativi e Narrativi", "icon": "🎭", "adult": False, "premium": False, "description": "Narratori, sceneggiatori e game master per esperienze creative immersive"},
    {"id": "quotidiano", "name": "Vita Quotidiana", "icon": "📋", "adult": False, "premium": False, "description": "Assistenti pratici per organizzazione casa, lavoro e vita di tutti i giorni"},
    {"id": "premium", "name": "Premium", "icon": "💎", "adult": False, "premium": True, "description": "Consulenti strategici e assistenti evoluti di alto livello"},
    {"id": "intrattenimento", "name": "Intrattenimento", "icon": "🎲", "adult": False, "premium": False, "description": "Personaggi divertenti e coinvolgenti per conversazioni innovative"},
    {"id": "speciale", "name": "Speciale", "icon": "❓", "adult": False, "premium": False, "description": "Personaggi speciali, sperimentali e personalizzabili dall'utente"},
]
